title: Wojciech Mierzynski 
logo: "/images/headshot2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  As a Master's graduate in International Business Administration specializing in data science and technology management, I am highly motivated to leverage my expertise and practical knowledge in a Data Analyst capacity. I bring proficiency in MS Excel, MySQL, RStudio, Python, and Tableau, as well as experience in project management and collaborative teamwork.
  <br><br>
  <a href="https://www.linkedin.com/in/wojciech-mierzynski-1995521b4/">View my LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'  


  
  

